name:                hw00
version:             0.1.0.0
github:              "MI-PYT/hw00"
license:             MIT
author:              "Marek Suchánek"
maintainer:          "marek.suchanek@fit.cvut.cz"
copyright:           "2018 Marek Suchánek"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Dummy homework for explanation and showing the workflow

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  hw00-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hw00

tests:
  hw00-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hw00
    - hspec == 2.*
